#!/usr/bin/env bash
#
i=1
max=100
while ((i<=max))
do
  
   if ((i % 3 == 0 && i % 5 == 0))
   then
	   
	 echo "FizzBuzz"

 elif ((i % 3 == 0))
 then
	 echo "Fizz"
 elif ((i % 5 == 0))
 then
	 echo "Buzz"
 else
echo $i	 
   fi
   
   ((i++))
 
done
