#!/usr/bin/env bash
#
while IFS=: read -r username password userid groupid comment homedir cmdshell
 

#   while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
   do
   echo $username":"$userid$homedir
# | cut -d /$f1/
done < /etc/passwd

