#!/usr/bin/env bash
#This will display a script of numbers 1-20 in which after 4 it will display bad luck from CHina, after 9 it will display bad luck from Japan, and finally after 17 it will display bad luck from Italy.

n=1
max=20
while (( $n<=$max))
do
   echo $n
   ((n++))

   case $n in
	   "5" ) echo "bad luck from China"
	      ;;
	     "10" ) echo "bad luck from Japan"
		     ;;
           "18" ) echo "bad luck from Italy"
		   ;;
esac
done
