#!/usr/bin/env bash
#In this script we will simulate a clock and print out minutes 0-59 and hours 1-12
n=0
max=58
h=0
hmax=12
while (( h<=hmax))
do
     
      echo -e "Hour: $h"
      for i in {1..59}
      do
	      echo $i
      done
      ((h++))

done 
