#!/usr/bin/env bash
#COmment
FILE=school

if test -f "$FILE";
then
echo "school file exists"

   if test -s "$FILE";
   then
        echo "school file is not empty"
   else
        echo "school file is empty"

   fi
   else
        echo "school file does not exist"
   fi
    

